import {
  useEffect,
  useState,
} from "react";

import {
  useParams,
} from "react-router-dom";
import toast from "react-hot-toast";
import API from "../services/api";

const RecruiterNotes = ({ application, fetchApplicants }) => {
  const [notes, setNotes] = useState(application.recruiterNotes || "");
  const [saving, setSaving] = useState(false);

  const handleSave = async () => {
    setSaving(true);
    try {
      await API.put(`/application/${application.id}/notes`, { notes });
      toast.success("Notes saved");
      fetchApplicants();
    } catch (err) {
      toast.error("Failed to save notes");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="mt-5 bg-slate-900 p-4 rounded-xl border border-slate-700">
      <h4 className="font-bold text-blue-300 mb-2">Private Recruiter Notes</h4>
      <textarea
        className="w-full bg-slate-800 p-3 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
        rows="3"
        value={notes}
        onChange={(e) => setNotes(e.target.value)}
        placeholder="Add private notes about this candidate..."
      ></textarea>
      <button
        onClick={handleSave}
        disabled={saving}
        className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded mt-2 text-sm transition-colors"
      >
        {saving ? "Saving..." : "Save Notes"}
      </button>
    </div>
  );
};

const InterviewQuestions = ({ application }) => {
  const [questions, setQuestions] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await API.get(`/ai/interview-questions/${application.id}`);
      setQuestions(res.data);
      toast.success("Questions generated by Gemini");
    } catch (error) {
      toast.error("Failed to generate questions");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mt-5 bg-slate-900 p-4 rounded-xl border border-slate-700">
      <div className="flex justify-between items-center mb-4">
        <h4 className="font-bold text-purple-400 flex items-center gap-2">
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
          Gemini AI Interview Prep
        </h4>
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="bg-purple-600 hover:bg-purple-700 px-4 py-2 rounded text-sm transition-colors flex items-center gap-2 disabled:opacity-50"
        >
          {loading ? "Generating..." : "Generate Guide"}
        </button>
      </div>

      {questions && (
        <div className="space-y-4 animate-in fade-in duration-300">
          {questions.technical?.length > 0 && (
            <div>
              <h5 className="font-semibold text-blue-300 text-sm uppercase tracking-wider mb-2">Technical Questions</h5>
              <ul className="list-disc ml-5 space-y-1 text-slate-300 text-sm">
                {questions.technical.map((q, i) => <li key={i}>{q}</li>)}
              </ul>
            </div>
          )}
          {questions.hr?.length > 0 && (
            <div>
              <h5 className="font-semibold text-green-300 text-sm uppercase tracking-wider mb-2">HR Questions</h5>
              <ul className="list-disc ml-5 space-y-1 text-slate-300 text-sm">
                {questions.hr.map((q, i) => <li key={i}>{q}</li>)}
              </ul>
            </div>
          )}
          {questions.scenario?.length > 0 && (
            <div>
              <h5 className="font-semibold text-yellow-300 text-sm uppercase tracking-wider mb-2">Scenario</h5>
              <ul className="list-disc ml-5 space-y-1 text-slate-300 text-sm">
                {questions.scenario.map((q, i) => <li key={i}>{q}</li>)}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

const ScheduleInterview = ({ application, fetchApplicants }) => {
  const [date, setDate] = useState(application.interviewDate ? application.interviewDate.slice(0, 16) : "");
  const [link, setLink] = useState(application.interviewLink || "");
  const [saving, setSaving] = useState(false);

  const handleSave = async () => {
    setSaving(true);
    try {
      await API.put(`/application/${application.id}/interview`, { date: new Date(date).toISOString(), link });
      toast.success("Interview scheduled successfully");
      fetchApplicants();
    } catch (error) {
      toast.error("Failed to schedule interview");
    } finally {
      setSaving(false);
    }
  };

  if (application.status !== "INTERVIEW_SCHEDULED") return null;

  return (
    <div className="mt-5 bg-slate-900 p-4 rounded-xl border border-slate-700 animate-in fade-in duration-300">
      <h4 className="font-bold text-teal-400 mb-4 flex items-center gap-2">
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
        Schedule Interview
      </h4>
      <div className="space-y-3">
        <div>
          <label className="block text-slate-400 text-sm mb-1">Date & Time</label>
          <input
            type="datetime-local"
            value={date}
            onChange={(e) => setDate(e.target.value)}
            className="w-full bg-slate-800 p-2 rounded-lg text-white border border-slate-700 focus:border-teal-500 focus:outline-none"
          />
        </div>
        <div>
          <label className="block text-slate-400 text-sm mb-1">Meeting Link (e.g. Google Meet)</label>
          <input
            type="url"
            value={link}
            onChange={(e) => setLink(e.target.value)}
            placeholder="https://meet.google.com/..."
            className="w-full bg-slate-800 p-2 rounded-lg text-white border border-slate-700 focus:border-teal-500 focus:outline-none"
          />
        </div>
        <button
          onClick={handleSave}
          disabled={saving || !date}
          className="bg-teal-600 hover:bg-teal-700 px-4 py-2 rounded text-sm transition-colors w-full disabled:opacity-50 mt-2"
        >
          {saving ? "Saving..." : "Save Schedule"}
        </button>
      </div>
    </div>
  );
};

const Applicants = () => {

  const { jobId } =
    useParams();

  const [applications, setApplications] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");

  const fetchApplicants = async () => {
    try {
      const res = await API.get(`/jobs/${jobId}/applicants`);
      setApplications(res.data);
    } catch {
      toast.error("Failed to fetch applicants");
    }
  };

  const updateStatus = async (applicationId, status) => {
    try {
      await API.put(`/application/${applicationId}/status`, { status });
      toast.success(`Application ${status.toLowerCase()}`);
      fetchApplicants();
    } catch (error) {
      toast.error(error.response?.data?.message || "Something went wrong");
    }
  };

  useEffect(() => {
    fetchApplicants();
  }, []);

  const filteredApplications = applications.filter((app) => {
    const matchesSearch =
      app.candidate.fullName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      app.candidate.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (app.candidate.candidateProfile?.skills || []).some(s => s.toLowerCase().includes(searchTerm.toLowerCase()));
    
    const matchesStatus = statusFilter === "ALL" || app.status === statusFilter;
    
    return matchesSearch && matchesStatus;
  });

  return (
    <div className="p-10 max-w-7xl mx-auto">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-10 gap-4">
        <h1 className="text-4xl font-bold text-white">Applicants</h1>
        
        <div className="flex flex-wrap gap-4">
          <input
            type="text"
            placeholder="Search name, email, or skills..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="bg-slate-800 text-white px-4 py-2 rounded-lg border border-slate-700 focus:outline-none focus:border-blue-500 w-64"
          />
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-slate-800 text-white px-4 py-2 rounded-lg border border-slate-700 focus:outline-none focus:border-blue-500"
          >
            <option value="ALL">All Statuses</option>
            <option value="APPLIED">Applied</option>
            <option value="SHORTLISTED">Shortlisted</option>
            <option value="REJECTED">Rejected</option>
          </select>
        </div>
      </div>

      {filteredApplications.length === 0 ? (
        <div className="text-center py-20 text-slate-400">
          <p className="text-xl">No applicants found matching your criteria.</p>
        </div>
      ) : (
      <div
        className="
        grid
        md:grid-cols-2
        gap-6
        "
      >

        {filteredApplications.map(
          (application) => (

            <div
              key={application.id}
              className="
              bg-slate-800
              p-6
              rounded-xl
              "
            >

              <h2
                className="
                text-2xl
                font-bold
                "
              >
                {
                  application
                  .candidate
                  .fullName
                }
              </h2>

              <p className="mt-2">
                {
                  application
                  .candidate
                  .email
                }
              </p>

              <p className="mt-4">
                Match Score:

                <span
                  className="
                  text-green-400
                  font-bold
                  "
                >
                  {" "}
                  {
                    application
                    .matchScore
                  }%
                </span>
              </p>

              <p className="mt-2">

                {
                  application
                  .aiFeedback
                }

              </p>

              <div
                className="
                bg-slate-900
                p-4
                rounded-xl
                mt-5
                "
              >

                <h3
                  className="
                  text-xl
                  font-bold
                  mb-3
                  text-blue-400
                  "
                >
                  AI Evaluation
                </h3>

                <p className="mb-3">

                  <span
                    className="
                    font-bold
                    "
                  >
                    Summary:
                  </span>

                  {" "}

                  {
                    application
                    .candidate
                    .candidateProfile
                    ?.professionalSummary
                  }

                </p>

                <div className="mb-3">

                  <h4
                    className="
                    font-bold
                    text-green-400
                    mb-2
                    "
                  >
                    Strengths
                  </h4>

                  <ul
                    className="
                    list-disc
                    ml-6
                    "
                  >

                    {
                      application
                      .candidate
                      .candidateProfile
                      ?.strengths
                      ?.map(
                        (
                          strength,
                          index
                        ) => (

                          <li
                            key={index}
                          >
                            {strength}
                          </li>
                        )
                      )
                    }

                  </ul>

                </div>

                <div className="mb-3">

                  <h4
                    className="
                    font-bold
                    text-red-400
                    mb-2
                    "
                  >
                    Weaknesses
                  </h4>

                  <ul
                    className="
                    list-disc
                    ml-6
                    "
                  >

                    {
                      application
                      .candidate
                      .candidateProfile
                      ?.weaknesses
                      ?.map(
                        (
                          weakness,
                          index
                        ) => (

                          <li
                            key={index}
                          >
                            {weakness}
                          </li>
                        )
                      )
                    }

                  </ul>

                </div>

                <p
                  className="
                  mt-4
                  text-yellow-300
                  font-bold
                  "
                >

                  Recommendation:

                  {" "}

                  {
                    application
                    .candidate
                    .candidateProfile
                    ?.hiringRecommendation
                  }

                </p>

              </div>

              <p className="mt-3">

                Status:

                <span
                  className="
                  font-bold
                  text-yellow-400
                  "
                >
                  {" "}
                  {
                    application
                    .status
                  }
                </span>

              </p>

              <div className="flex flex-col gap-2 mt-5">
                <label className="text-sm font-bold text-slate-400">Update Pipeline Status:</label>
                <select
                  value={application.status}
                  onChange={(e) => updateStatus(application.id, e.target.value)}
                  className="bg-slate-900 border border-slate-700 text-white px-4 py-2 rounded-lg focus:outline-none focus:border-blue-500 transition-colors"
                >
                  <option value="APPLIED">Applied</option>
                  <option value="REVIEWING">Reviewing</option>
                  <option value="SHORTLISTED">Shortlisted</option>
                  <option value="INTERVIEW_SCHEDULED">Interview Scheduled</option>
                  <option value="INTERVIEWED">Interviewed</option>
                  <option value="SELECTED">Selected</option>
                  <option value="REJECTED">Rejected</option>
                  <option value="HIRED">Hired</option>
                </select>
              </div>

              <RecruiterNotes application={application} fetchApplicants={fetchApplicants} />
              
              <ScheduleInterview application={application} fetchApplicants={fetchApplicants} />

              <InterviewQuestions application={application} />

              <div
                className="
                flex
                flex-wrap
                gap-2
                mt-4
                "
              >

                {
                  application
                  .candidate
                  .candidateProfile
                  ?.skills
                  ?.length > 0 ? (

                    application
                    .candidate
                    .candidateProfile
                    ?.skills
                    ?.map(
                      (
                        skill,
                        index
                      ) => (

                        <span
                          key={index}
                          className="
                          bg-blue-600
                          px-3
                          py-1
                          rounded-full
                          text-sm
                          "
                        >
                          {skill}
                        </span>
                      )
                    )

                  ) : (

                    <p>
                      No resume skills found
                    </p>
                  )
                }

              </div>

              {
                application
                .candidate
                .candidateProfile
                ?.resumeUrl && (

                  <a href={application.candidate.candidateProfile.resumeUrl} target="_blank" rel="noreferrer"
                    className="
                    inline-block
                    bg-green-600
                    px-5
                    py-2
                    rounded
                    mt-5
                    "
                  >
                    View Resume
                  </a>
                )
              }

            </div>
          )
        )}

      </div>
      )}
    </div>
  );
};

export default Applicants;