import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import toast from "react-hot-toast";
import API from "../services/api";
import { motion, AnimatePresence } from "framer-motion";
import {
  FileText,
  Calendar,
  Sparkles,
  Search,
  SlidersHorizontal,
  Bookmark,
  ChevronDown,
  Download,
  Award,
  BookOpen,
  ArrowRight,
  TrendingUp,
  Brain,
  UserCheck,
  UserX,
  X,
  FileCheck,
  Activity,
  Layers,
  GraduationCap
} from "lucide-react";

const RecruiterNotes = ({ application, fetchApplicants }) => {
  const [notes, setNotes] = useState(application.recruiterNotes || "");
  const [saving, setSaving] = useState(false);

  const handleSave = async () => {
    setSaving(true);
    try {
      await API.put(`/application/${application.id}/notes`, { notes });
      toast.success("Notes saved successfully");
      fetchApplicants();
    } catch (err) {
      toast.error("Failed to save notes");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="mt-5 bg-slate-950/60 p-4 rounded-2xl border border-slate-850">
      <h4 className="font-bold text-blue-400 mb-2.5 text-xs uppercase tracking-wider flex items-center gap-1.5">
        📝 Private Evaluation Notes
      </h4>
      <textarea
        className="w-full bg-slate-900 border border-slate-850 p-3 rounded-xl text-slate-200 text-xs focus:outline-none focus:border-blue-500 leading-relaxed"
        rows="3"
        value={notes}
        onChange={(e) => setNotes(e.target.value)}
        placeholder="Add private evaluation feedback about this candidate..."
      ></textarea>
      <button
        onClick={handleSave}
        disabled={saving}
        className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-xl mt-2 text-xs font-bold transition-colors cursor-pointer"
      >
        {saving ? "Saving..." : "Save Notes"}
      </button>
    </div>
  );
};

const InterviewQuestions = ({ application }) => {
  const [questions, setQuestions] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await API.get(`/ai/interview-questions/${application.id}`);
      setQuestions(res.data);
      toast.success("Questions generated by Gemini");
    } catch (error) {
      toast.error("Failed to generate questions");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mt-5 bg-slate-950/60 p-4 rounded-2xl border border-slate-850">
      <div className="flex justify-between items-center mb-4">
        <h4 className="font-bold text-purple-400 text-xs uppercase tracking-wider flex items-center gap-1.5">
          <Brain size={14} className="text-purple-400" /> AI Interview Prep Guide
        </h4>
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="bg-purple-600 hover:bg-purple-500 px-4 py-1.5 rounded-xl text-[10px] font-extrabold tracking-wide uppercase transition-colors disabled:opacity-50 cursor-pointer"
        >
          {loading ? "Generating..." : "Generate Guide"}
        </button>
      </div>

      <AnimatePresence>
        {questions && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="space-y-4 text-xs mt-2"
          >
            {questions.technical?.length > 0 && (
              <div className="bg-slate-900/60 p-3.5 rounded-xl border border-slate-850">
                <h5 className="font-bold text-blue-400 uppercase text-[9px] tracking-wider mb-2">Technical Core questions</h5>
                <ul className="list-disc ml-4 space-y-1.5 text-slate-300 leading-normal">
                  {questions.technical.map((q, i) => <li key={i}>{q}</li>)}
                </ul>
              </div>
            )}
            {questions.hr?.length > 0 && (
              <div className="bg-slate-900/60 p-3.5 rounded-xl border border-slate-850">
                <h5 className="font-bold text-green-400 uppercase text-[9px] tracking-wider mb-2">Behavioral / HR questions</h5>
                <ul className="list-disc ml-4 space-y-1.5 text-slate-300 leading-normal">
                  {questions.hr.map((q, i) => <li key={i}>{q}</li>)}
                </ul>
              </div>
            )}
            {questions.scenario?.length > 0 && (
              <div className="bg-slate-900/60 p-3.5 rounded-xl border border-slate-850">
                <h5 className="font-bold text-yellow-500 uppercase text-[9px] tracking-wider mb-2">Scenario Analysis</h5>
                <ul className="list-disc ml-4 space-y-1.5 text-slate-300 leading-normal">
                  {questions.scenario.map((q, i) => <li key={i}>{q}</li>)}
                </ul>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

const ScheduleInterview = ({ application, fetchApplicants }) => {
  const [date, setDate] = useState(application.interviewDate ? application.interviewDate.slice(0, 16) : "");
  const [time, setTime] = useState(application.interviewTime || "");
  const [link, setLink] = useState(application.interviewLink || "");
  const [notes, setNotes] = useState(application.interviewerNotes || "");
  const [saving, setSaving] = useState(false);

  const handleSave = async () => {
    setSaving(true);
    try {
      await API.put(`/application/${application.id}/interview`, {
        interviewDate: new Date(date).toISOString(),
        interviewTime: time,
        interviewLink: link,
        interviewerNotes: notes,
      });
      toast.success("Interview scheduled successfully!");
      fetchApplicants();
    } catch (error) {
      toast.error("Failed to schedule interview");
    } finally {
      setSaving(false);
    }
  };

  if (application.status !== "INTERVIEW_SCHEDULED") return null;

  return (
    <div className="mt-5 bg-slate-950/60 p-4 rounded-2xl border border-blue-500/10 text-xs space-y-3.5">
      <h4 className="font-bold text-blue-400 flex items-center gap-1.5 text-xs uppercase tracking-wider border-b border-slate-900 pb-2">
        📅 Set Meeting Schedule
      </h4>
      <div className="space-y-3">
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="block text-slate-400 mb-1 font-semibold text-[10px] uppercase">Date</label>
            <input
              type="datetime-local"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className="w-full bg-slate-900 p-2.5 rounded-lg text-slate-200 border border-slate-800 focus:border-blue-500 focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-slate-400 mb-1 font-semibold text-[10px] uppercase">Time Frame</label>
            <input
              type="text"
              value={time}
              onChange={(e) => setTime(e.target.value)}
              placeholder="e.g. 10:30 AM"
              className="w-full bg-slate-900 p-2.5 rounded-lg text-slate-200 border border-slate-800 focus:border-blue-500 focus:outline-none"
            />
          </div>
        </div>
        <div>
          <label className="block text-slate-400 mb-1 font-semibold text-[10px] uppercase">Meeting Link (Zoom / Meet)</label>
          <input
            type="url"
            value={link}
            onChange={(e) => setLink(e.target.value)}
            placeholder="https://meet.google.com/..."
            className="w-full bg-slate-900 p-2.5 rounded-lg text-slate-200 border border-slate-800 focus:border-blue-500 focus:outline-none font-mono text-[10px]"
          />
        </div>
        <div>
          <label className="block text-slate-400 mb-1 font-semibold text-[10px] uppercase">Meeting Guidelines</label>
          <input
            type="text"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Bring resume, portfolio, CKA details..."
            className="w-full bg-slate-900 p-2.5 rounded-lg text-slate-200 border border-slate-800 focus:border-blue-500 focus:outline-none"
          />
        </div>
        <button
          onClick={handleSave}
          disabled={saving || !date || !link}
          className="bg-blue-600 hover:bg-blue-500 px-4 py-2.5 rounded-xl text-white font-bold w-full transition-colors disabled:opacity-50 mt-1 cursor-pointer"
        >
          {saving ? "Scheduling..." : "Send Invite & Schedule"}
        </button>
      </div>
    </div>
  );
};

const Applicants = () => {
  const { jobId } = useParams();
  const [applications, setApplications] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [minScore, setMinScore] = useState(0);

  // Compare candidates state
  const [selectedIds, setSelectedIds] = useState([]);
  const [comparisonResult, setComparisonResult] = useState(null);
  const [loadingComparison, setLoadingComparison] = useState(false);
  const [showCompareModal, setShowCompareModal] = useState(false);

  // AI Candidate Ranking states
  const [rankedCandidates, setRankedCandidates] = useState(null);
  const [rankingLoading, setRankingLoading] = useState(false);
  const [viewMode, setViewMode] = useState("standard"); // "standard" or "ai"
  const [sortBy, setSortBy] = useState("score"); // "score", "date", "name"

  // Offer Letter states
  const [showOfferModal, setShowOfferModal] = useState(false);
  const [selectedAppForOffer, setSelectedAppForOffer] = useState(null);
  const [offerSalary, setOfferSalary] = useState("");
  const [offerJoiningDate, setOfferJoiningDate] = useState("");
  const [offerRole, setOfferRole] = useState("");
  const [offerCompanyName, setOfferCompanyName] = useState("");
  const [generatingOffer, setGeneratingOffer] = useState(false);

  const handleGenerateOfferSubmit = async (e) => {
    e.preventDefault();
    if (!selectedAppForOffer) return;
    setGeneratingOffer(true);
    try {
      const res = await API.post(`/application/${selectedAppForOffer.id}/offer-letter`, {
        salary: offerSalary,
        joiningDate: offerJoiningDate,
        role: offerRole,
        companyName: offerCompanyName,
      });
      if (res.data.application) {
        toast.success("Offer Letter issued successfully!");
        setShowOfferModal(false);
        setSelectedAppForOffer(null);
        setOfferSalary("");
        setOfferJoiningDate("");
        fetchApplicants();
      }
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate and issue offer letter");
    } finally {
      setGeneratingOffer(false);
    }
  };

  const fetchApplicants = async () => {
    try {
      const res = await API.get(`/jobs/${jobId}/applicants`);
      setApplications(res.data);
    } catch {
      toast.error("Failed to fetch applicants");
    }
  };

  const updateStatus = async (applicationId, status) => {
    try {
      await API.put(`/application/${applicationId}/status`, { status });
      toast.success(`Application stage changed to ${status.toLowerCase()}`);
      fetchApplicants();
    } catch (error) {
      toast.error(error.response?.data?.message || "Something went wrong");
    }
  };

  const handleAIRank = async () => {
    setRankingLoading(true);
    try {
      const res = await API.post("/recruiter/rank-candidates", { jobId });
      if (res.data.success) {
        setRankedCandidates(res.data.data);
        setViewMode("ai");
        toast.success("Candidates ranked by Gemini AI!");
      }
    } catch (err) {
      console.error(err);
      toast.error("Failed to rank candidates via AI");
    } finally {
      setRankingLoading(false);
    }
  };

  useEffect(() => {
    fetchApplicants();
  }, []);

  const filteredApplications = applications.filter((app) => {
    const matchesSearch =
      app.candidate.fullName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      app.candidate.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (app.candidate.candidateProfile?.skills || []).some(s => s.toLowerCase().includes(searchTerm.toLowerCase()));
    
    const matchesStatus = statusFilter === "ALL" || app.status === statusFilter;
    const matchesScore = (app.matchScore || 0) >= minScore;
    
    return matchesSearch && matchesStatus && matchesScore;
  });

  const getSortedApplications = () => {
    let list = [...filteredApplications];
    if (sortBy === "score") {
      list.sort((a, b) => (b.matchScore || 0) - (a.matchScore || 0));
    } else if (sortBy === "date") {
      list.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
    } else if (sortBy === "name") {
      list.sort((a, b) => a.candidate.fullName.localeCompare(b.candidate.fullName));
    }
    return list;
  };

  const getSortedRanked = () => {
    if (!rankedCandidates) return [];
    let list = [...rankedCandidates];
    if (sortBy === "score") {
      list.sort((a, b) => b.fitScore - a.fitScore);
    } else if (sortBy === "name") {
      list.sort((a, b) => a.name.localeCompare(b.name));
    }
    return list;
  };

  // Checkbox select toggle
  const handleSelectCandidate = (candidateId) => {
    if (selectedIds.includes(candidateId)) {
      setSelectedIds(prev => prev.filter(id => id !== candidateId));
    } else {
      if (selectedIds.length >= 2) {
        toast.error("You can select maximum 2 candidates to compare.");
        return;
      }
      setSelectedIds(prev => [...prev, candidateId]);
    }
  };

  // AI comparison trigger
  const runCandidateComparison = async () => {
    if (selectedIds.length !== 2) {
      toast.error("Please select exactly 2 candidates to compare.");
      return;
    }
    setLoadingComparison(true);
    setShowCompareModal(true);
    try {
      const res = await API.post("/ai/compare", {
        candidateId1: selectedIds[0],
        candidateId2: selectedIds[1],
        jobId,
      });
      setComparisonResult(res.data);
    } catch (err) {
      toast.error("Failed to generate AI candidate comparison.");
      setShowCompareModal(false);
    } finally {
      setLoadingComparison(false);
    }
  };

  // Export CSV Action
  const exportCSV = () => {
    if (filteredApplications.length === 0) return toast.error("No applicants to export");
    const headers = ["Candidate Name", "Email", "Match Score %", "Status", "Skills", "Applied Date"];
    const rows = filteredApplications.map(app => [
      app.candidate.fullName,
      app.candidate.email,
      app.matchScore || 0,
      app.status,
      (app.candidate.candidateProfile?.skills || []).join("; "),
      new Date(app.createdAt).toLocaleDateString(),
    ]);

    const csvContent = "data:text/csv;charset=utf-8," 
      + [headers.join(","), ...rows.map(e => e.map(val => `"${val}"`).join(","))].join("\n");
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `applicants_job_${jobId}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("CSV file downloaded successfully!");
  };

  // Export Excel Action (TSV formatted as .xls for Excel loading)
  const exportExcel = () => {
    if (filteredApplications.length === 0) return toast.error("No applicants to export");
    const headers = ["Candidate Name", "\tEmail", "\tMatch Score %", "\tStatus", "\tSkills", "\tApplied Date"];
    const rows = filteredApplications.map(app => [
      app.candidate.fullName,
      `\t${app.candidate.email}`,
      `\t${app.matchScore || 0}`,
      `\t${app.status}`,
      `\t${(app.candidate.candidateProfile?.skills || []).join("; ")}`,
      `\t${new Date(app.createdAt).toLocaleDateString()}`,
    ]);

    const excelContent = [headers.join("\t"), ...rows.map(e => e.join("\t"))].join("\n");
    const blob = new Blob([excelContent], { type: "application/vnd.ms-excel" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `applicants_job_${jobId}.xls`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("Excel sheet downloaded successfully!");
  };

  const renderVisualMatchBar = (percentageStr) => {
    const val = parseInt(percentageStr) || 50;
    const blocksCount = Math.round(val / 8);
    const filledBlocks = "█".repeat(blocksCount);
    const emptyBlocks = "░".repeat(12 - blocksCount);
    return `${filledBlocks}${emptyBlocks}`;
  };

  return (
    <div className="p-6 md:p-10 max-w-7xl mx-auto space-y-8 text-slate-100 min-h-screen">
      
      {/* Title Header */}
      <div className="flex flex-col xl:flex-row justify-between items-start xl:items-center gap-6 border-b border-slate-900 pb-6">
        <div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight bg-gradient-to-r from-blue-400 to-indigo-400 bg-clip-text text-transparent">
            Applicant Evaluation Board
          </h1>
          <p className="text-slate-400 text-xs md:text-sm mt-1">Review matches scores, run side-by-side candidate comparisons, and issue official offers.</p>
        </div>
        
        {/* Buttons Row */}
        <div className="flex flex-wrap gap-2.5 items-center w-full xl:w-auto">
          <Link
            to={`/recruiter/pipeline/${jobId}`}
            className="bg-slate-900 hover:bg-slate-800 text-slate-300 font-bold px-4.5 py-2.5 rounded-xl border border-slate-850 transition-all text-xs cursor-pointer"
          >
            📋 Kanban Pipeline
          </Link>

          <button
            onClick={handleAIRank}
            disabled={rankingLoading || applications.length === 0}
            className="bg-purple-600 hover:bg-purple-500 text-white font-bold px-4.5 py-2.5 rounded-xl transition-all text-xs flex items-center gap-1.5 cursor-pointer shadow-md shadow-purple-500/10"
          >
            <Sparkles size={13} /> AI Rank Applicants
          </button>

          <button
            onClick={runCandidateComparison}
            disabled={selectedIds.length !== 2}
            className="bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 text-white font-bold px-4.5 py-2.5 rounded-xl transition-all text-xs cursor-pointer shadow-md shadow-indigo-500/10"
          >
            👥 Compare Selected ({selectedIds.length}/2)
          </button>
          
          <button onClick={exportCSV} className="bg-slate-900 hover:bg-slate-850 text-slate-400 hover:text-white px-4 py-2.5 rounded-xl text-xs transition-colors border border-slate-850 font-bold cursor-pointer">
            CSV Export
          </button>
          <button onClick={exportExcel} className="bg-slate-900 hover:bg-slate-850 text-slate-400 hover:text-white px-4 py-2.5 rounded-xl text-xs transition-colors border border-slate-850 font-bold cursor-pointer">
            Excel Export
          </button>
        </div>
      </div>

      {rankingLoading && (
        <div className="flex flex-col items-center justify-center py-20 bg-slate-900/60 border border-slate-850 rounded-3xl animate-pulse">
          <div className="w-10 h-10 border-3 border-purple-500 border-t-transparent rounded-full animate-spin mb-4"></div>
          <p className="text-slate-400 font-semibold text-xs">Gemini AI is parsing resumes data and generating applicant ranking table...</p>
        </div>
      )}

      {/* Advanced Filter Panel */}
      {!rankingLoading && (
        <div className="bg-slate-900/60 backdrop-blur-md p-6 rounded-3xl border border-slate-850 space-y-6 text-xs font-semibold text-left">
          <div className="flex justify-between items-center border-b border-slate-950 pb-3.5">
            <div className="flex gap-4">
              <button
                onClick={() => setViewMode("standard")}
                className={`font-bold py-1 px-3.5 rounded-xl transition-all border cursor-pointer ${
                  viewMode === "standard"
                    ? "bg-blue-600 text-white border-blue-500 shadow-md shadow-blue-500/10"
                    : "bg-slate-950 text-slate-500 border-slate-850 hover:text-slate-300"
                }`}
              >
                Standard Sourcing
              </button>
              {rankedCandidates && (
                <button
                  onClick={() => setViewMode("ai")}
                  className={`font-bold py-1 px-3.5 rounded-xl transition-all border cursor-pointer ${
                    viewMode === "ai"
                      ? "bg-purple-600 text-white border-purple-500 shadow-md shadow-purple-500/10"
                      : "bg-slate-950 text-slate-500 border-slate-850 hover:text-slate-350"
                  }`}
                >
                  🤖 Gemini AI Ranked
                </button>
              )}
            </div>

            {/* Sort Dropdowns */}
            <div className="flex items-center gap-2">
              <span className="text-slate-500 font-bold uppercase tracking-wider text-[10px]">Sort List:</span>
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="bg-slate-950 border border-slate-850 text-slate-200 rounded-lg p-2 text-xs font-bold focus:outline-none"
              >
                <option value="score">AI Match Rating</option>
                {viewMode === "standard" && <option value="date">Applied Date</option>}
                <option value="name">Candidate Name</option>
              </select>
            </div>
          </div>

          {viewMode === "standard" && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-end">
              <div>
                <label className="block text-slate-400 mb-2 font-bold uppercase tracking-wider text-[10px]">Search Candidates</label>
                <div className="relative">
                  <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
                  <input
                    type="text"
                    placeholder="Search name, email, or skills..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-855 rounded-xl pl-9 pr-4 py-2.5 text-slate-200 focus:outline-none focus:border-blue-500"
                  />
                </div>
              </div>

              <div>
                <label className="block text-slate-400 mb-2 font-bold uppercase tracking-wider text-[10px]">Filter Status Stage</label>
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-855 rounded-xl px-4 py-2.5 text-slate-200 focus:outline-none focus:border-blue-500 font-bold"
                >
                  <option value="ALL">All Stages</option>
                  <option value="APPLIED">Applied</option>
                  <option value="REVIEWING">Reviewing</option>
                  <option value="SHORTLISTED">Shortlisted</option>
                  <option value="INTERVIEW_SCHEDULED">Interview Scheduled</option>
                  <option value="INTERVIEWED">Interviewed</option>
                  <option value="SELECTED">Selected</option>
                  <option value="REJECTED">Rejected</option>
                  <option value="HIRED">Hired</option>
                </select>
              </div>

              <div>
                <div className="flex justify-between text-slate-400 mb-2 font-bold uppercase tracking-wider text-[10px]">
                  <span>Minimum Match Ratio</span>
                  <span className="text-blue-400">{minScore}% Match</span>
                </div>
                <input
                  type="range"
                  min="0"
                  max="100"
                  value={minScore}
                  onChange={(e) => setMinScore(Number(e.target.value))}
                  className="w-full h-1.5 bg-slate-950 rounded-lg appearance-none cursor-pointer accent-blue-500"
                />
              </div>
            </div>
          )}
        </div>
      )}

      {/* Render Applicants Cards */}
      {!rankingLoading && (
        <AnimatePresence mode="wait">
          {viewMode === "standard" ? (
            filteredApplications.length === 0 ? (
              <p className="text-center py-20 bg-slate-900/20 rounded-3xl border border-slate-850 text-slate-500 text-xs font-semibold">
                No candidates match your filters criteria.
              </p>
            ) : (
              <motion.div
                key="standard-list"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="grid grid-cols-1 md:grid-cols-2 gap-6 text-left"
              >
                {getSortedApplications().map((application) => {
                  const isSelected = selectedIds.includes(application.candidateId);
                  return (
                    <motion.div
                      layout
                      key={application.id}
                      className={`bg-slate-900/40 backdrop-blur-md p-6 rounded-3xl border transition-all relative flex flex-col justify-between space-y-6 ${
                        isSelected ? "border-indigo-500 ring-2 ring-indigo-950/80" : "border-slate-850 hover:border-slate-750"
                      }`}
                    >
                      <div>
                        {/* Selector checkbox */}
                        <div className="absolute top-6 right-6 flex items-center gap-2 bg-slate-950 px-2.5 py-1.5 rounded-xl border border-slate-850 text-[10px] font-bold">
                          <label className="text-slate-450 cursor-pointer" htmlFor={`check-${application.id}`}>Compare</label>
                          <input
                            type="checkbox"
                            id={`check-${application.id}`}
                            checked={isSelected}
                            onChange={() => handleSelectCandidate(application.candidateId)}
                            className="w-3.5 h-3.5 rounded bg-slate-900 border-slate-800 text-indigo-500 focus:ring-indigo-500 cursor-pointer"
                          />
                        </div>

                        <h2 className="text-xl font-extrabold text-white pr-24 truncate">{application.candidate.fullName}</h2>
                        <p className="text-xs text-slate-450 mt-0.5">{application.candidate.email}</p>

                        <div className="flex gap-4 text-xs mt-3.5">
                          <span className="text-blue-400 font-bold">🎯 Match Rating: {application.matchScore || 0}%</span>
                          <span className="text-slate-500 font-medium">Stage: <strong className="text-yellow-500">{application.status}</strong></span>
                        </div>

                        {application.aiFeedback && (
                          <div className="mt-4 p-3 bg-slate-950/50 rounded-xl border border-slate-850 text-[11px] text-slate-450 italic leading-relaxed">
                            " {application.aiFeedback} "
                          </div>
                        )}

                        {/* AI Summary and recommendation logs */}
                        <div className="bg-slate-950/70 p-4 rounded-xl border border-slate-850 text-[10px] leading-relaxed mt-4 space-y-3">
                          <h4 className="font-bold text-blue-400 text-xs flex items-center gap-1">
                            <Sparkles size={11} /> Recruiter AI Assessment
                          </h4>
                          {application.candidate.candidateProfile?.professionalSummary && (
                            <p className="text-slate-400">
                              <strong>Summary:</strong> {application.candidate.candidateProfile.professionalSummary}
                            </p>
                          )}
                          {application.candidate.candidateProfile?.hiringRecommendation && (
                            <p className="text-yellow-500 font-bold border-t border-slate-900 pt-2 mt-2">
                              💡 Gemini Rec: {application.candidate.candidateProfile.hiringRecommendation}
                            </p>
                          )}
                        </div>

                        {/* Verified documents list */}
                        <div className="bg-slate-950/70 p-4 rounded-xl border border-slate-850 text-[10px] leading-relaxed mt-4 space-y-3">
                          <h4 className="font-bold text-emerald-400 text-xs flex items-center gap-1">
                            <GraduationCap size={13} /> Verified Academic Credentials
                          </h4>
                          <div className="space-y-2">
                            <div className="flex justify-between items-center">
                              <span className="text-slate-400">Educational Degree:</span>
                              {application.candidate.candidateProfile?.degreeUrl ? (
                                <a
                                  href={application.candidate.candidateProfile.degreeUrl}
                                  target="_blank"
                                  rel="noreferrer"
                                  className="text-emerald-450 hover:underline font-bold"
                                >
                                  Degree PDF ↗
                                </a>
                              ) : (
                                <span className="text-slate-650 italic">Pending Upload</span>
                              )}
                            </div>
                            <div className="flex justify-between items-start gap-3">
                              <span className="text-slate-400">Certificates:</span>
                              {(() => {
                                const certs = application.candidate.candidateProfile?.certUrls;
                                let parsedCerts = [];
                                if (certs) {
                                  parsedCerts = Array.isArray(certs) 
                                    ? certs 
                                    : (typeof certs === 'string' ? JSON.parse(certs) : []);
                                }
                                if (parsedCerts.length === 0) {
                                  return <span className="text-slate-655 italic">Pending Upload</span>;
                                }
                                return (
                                  <ul className="list-none text-right space-y-1">
                                    {parsedCerts.map((c, idx) => (
                                      <li key={idx}>
                                        <a
                                          href={c.url}
                                          target="_blank"
                                          rel="noreferrer"
                                          className="text-blue-400 hover:underline font-bold"
                                        >
                                          {c.name || `Certificate ${idx + 1}`} ↗
                                        </a>
                                      </li>
                                    ))}
                                  </ul>
                                );
                              })()}
                            </div>
                          </div>
                        </div>

                        {/* Skills tags */}
                        <div className="flex flex-wrap gap-1 mt-4">
                          {(application.candidate.candidateProfile?.skills || []).map((s, idx) => (
                            <span key={idx} className="bg-slate-950 border border-slate-850 text-slate-400 px-2 py-0.5 rounded text-[9px] font-semibold">
                              {s}
                            </span>
                          ))}
                        </div>
                      </div>

                      <div className="space-y-4 pt-4 border-t border-slate-900">
                        {/* Selector status option */}
                        <div className="flex flex-col gap-1.5 text-[11px]">
                          <label className="font-bold text-slate-500">Pipeline status:</label>
                          <select
                            value={application.status}
                            onChange={(e) => updateStatus(application.id, e.target.value)}
                            className="bg-slate-950 border border-slate-850 text-slate-300 px-3.5 py-2 rounded-xl focus:outline-none focus:border-blue-500 font-bold"
                          >
                            <option value="APPLIED">Applied</option>
                            <option value="REVIEWING">Reviewing</option>
                            <option value="SHORTLISTED">Shortlisted</option>
                            <option value="INTERVIEW_SCHEDULED">Interview Scheduled</option>
                            <option value="INTERVIEWED">Interviewed</option>
                            <option value="SELECTED">Selected</option>
                            <option value="REJECTED">Rejected</option>
                            <option value="HIRED">Hired</option>
                          </select>
                        </div>

                        {/* Job Offer panel widget */}
                        <div className="bg-slate-950/60 p-3.5 rounded-xl border border-slate-850/60 text-[10px] space-y-2">
                          <div className="flex justify-between items-center">
                            <span className="font-bold text-blue-400 flex items-center gap-1"><FileCheck size={11} /> Offer Letter Status</span>
                            {application.offerLetterUrl && (
                              <span className="bg-green-500/10 text-green-400 font-bold px-1.5 py-0.5 rounded text-[8px] border border-green-500/15">Issued</span>
                            )}
                          </div>
                          {application.offerLetterUrl ? (
                            <div className="space-y-1.5">
                              <p className="text-slate-450 leading-relaxed">Official employment offer letter issued to candidate timeline.</p>
                              <a
                                href={application.offerLetterUrl}
                                target="_blank"
                                rel="noreferrer"
                                className="bg-blue-600/10 text-blue-400 border border-blue-900/20 hover:bg-blue-600 hover:text-white py-1 rounded-lg font-bold text-center block"
                              >
                                View Issued PDF ↗
                              </a>
                            </div>
                          ) : (
                            <button
                              onClick={() => {
                                setSelectedAppForOffer(application);
                                setOfferRole(application.job.title);
                                setOfferCompanyName(application.job.recruiter?.recruiterProfile?.companyName || "Accenture Corporate");
                                setShowOfferModal(true);
                              }}
                              className="w-full bg-slate-900 hover:bg-slate-850 text-slate-300 font-bold py-1.5 rounded-lg border border-slate-850 transition-colors"
                            >
                              Generate sealed PDF Offer Letter
                            </button>
                          )}
                        </div>

                        {/* Note scheduler and question widgets */}
                        <RecruiterNotes application={application} fetchApplicants={fetchApplicants} />
                        <ScheduleInterview application={application} fetchApplicants={fetchApplicants} />
                        <InterviewQuestions application={application} />

                        {application.candidate.candidateProfile?.resumeUrl && (
                          <a
                            href={application.candidate.candidateProfile.resumeUrl}
                            target="_blank"
                            rel="noreferrer"
                            className="bg-green-600 hover:bg-green-550 text-white font-bold py-2 rounded-xl text-xs w-full text-center block shadow transition-all active:scale-95"
                          >
                            View Candidate Resume ↗
                          </a>
                        )}
                      </div>
                    </motion.div>
                  );
                })}
              </motion.div>
            )
          ) : (
            <motion.div
              key="ai-list"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-5 text-left"
            >
              {getSortedRanked().map((candidate, index) => (
                <div key={candidate.candidateId} className="bg-slate-900/40 backdrop-blur-md p-6 rounded-3xl border border-purple-900/30 hover:border-purple-800 transition-colors shadow-lg">
                  <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-4">
                    <div>
                      <h3 className="text-lg font-bold text-white">
                        #{index + 1} {candidate.name}
                      </h3>
                      <p className="text-[10px] text-purple-400 font-bold uppercase tracking-wider mt-0.5">Rating Match: {candidate.fitPercentage}</p>
                    </div>

                    <div className="text-[10px] font-mono text-purple-300 bg-slate-950 px-3 py-1.5 rounded-xl border border-purple-950">
                      {renderVisualMatchBar(candidate.fitPercentage)} {candidate.fitScore}% Score
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4 text-[10px] leading-relaxed">
                    <div className="bg-slate-950 p-4 rounded-xl border border-slate-850">
                      <span className="font-bold text-green-400 uppercase tracking-wider block mb-2 text-[9px]">AI Highlight Strengths</span>
                      <div className="flex flex-wrap gap-1">
                        {candidate.strengths?.map((str, idx) => (
                          <span key={idx} className="bg-green-950/20 text-green-400 border border-green-900/10 px-2 py-0.5 rounded text-[9px] font-semibold">
                            {str}
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="bg-slate-950 p-4 rounded-xl border border-slate-850">
                      <span className="font-bold text-red-400 uppercase tracking-wider block mb-2 text-[9px]">AI Sourcing Concerns</span>
                      <div className="flex flex-wrap gap-1">
                        {candidate.concerns?.map((con, idx) => (
                          <span key={idx} className="bg-red-950/20 text-red-400 border border-red-900/10 px-2 py-0.5 rounded text-[9px] font-semibold">
                            {con}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>

                  <div className="bg-purple-950/5 p-4 rounded-xl border border-purple-500/10 text-xs text-slate-350 leading-relaxed">
                    <strong>Gemini AI Sourcing Evaluator:</strong> {candidate.recommendation}
                  </div>
                </div>
              ))}
            </motion.div>
          )}
        </AnimatePresence>
      )}

      {/* Comparison Modal overlay */}
      <AnimatePresence>
        {showCompareModal && (
          <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-6">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 15 }}
              transition={{ duration: 0.2 }}
              className="bg-slate-900 border border-slate-800 rounded-3xl max-w-4xl w-full max-h-[90vh] flex flex-col shadow-2xl overflow-hidden text-left"
            >
              <div className="flex justify-between items-center p-6 border-b border-slate-850 bg-slate-950/40">
                <h3 className="text-lg font-bold text-white flex items-center gap-1.5">
                  <Brain size={16} className="text-purple-400 animate-pulse" /> Gemini AI Side-by-Side Sourcing Comparison
                </h3>
                <button
                  onClick={() => {
                    setShowCompareModal(false);
                    setComparisonResult(null);
                  }}
                  className="text-slate-400 hover:text-white bg-slate-850 hover:bg-slate-800 p-2 rounded-xl text-xs font-bold border border-slate-800"
                >
                  ✕ Close
                </button>
              </div>

              <div className="flex-1 p-6 md:p-8 overflow-y-auto space-y-6 text-xs md:text-sm text-slate-350">
                {loadingComparison ? (
                  <div className="text-center py-20 space-y-4">
                    <div className="w-8 h-8 border-3 border-purple-500 border-t-transparent rounded-full animate-spin mx-auto"></div>
                    <p className="text-slate-400 text-xs font-semibold">Gemini AI is executing side-by-side applicants metrics parsing...</p>
                  </div>
                ) : comparisonResult ? (
                  <div className="space-y-6">
                    <div className="bg-slate-950 p-5 rounded-2xl border border-slate-850 leading-relaxed text-slate-300">
                      <h4 className="font-bold text-purple-400 text-xs uppercase tracking-wider mb-2">Comparison Overview Details</h4>
                      <p>{comparisonResult.comparison}</p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="bg-slate-950/50 p-5 rounded-2xl border border-slate-850 space-y-4">
                        <h4 className="font-bold text-white text-sm">Candidate A Comparison</h4>
                        <div className="space-y-3.5 text-xs">
                          <div>
                            <strong className="text-green-400 text-[9px] uppercase tracking-wider block mb-1">Fit Highlights</strong>
                            <ul className="list-disc pl-4 space-y-1 text-slate-400">
                              {(comparisonResult.strengthsA || []).map((s, idx) => <li key={idx}>{s}</li>)}
                            </ul>
                          </div>
                          <div>
                            <strong className="text-red-400 text-[9px] uppercase tracking-wider block mb-1">Gaps identified</strong>
                            <ul className="list-disc pl-4 space-y-1 text-slate-400">
                              {(comparisonResult.weaknessesA || []).map((w, idx) => <li key={idx}>{w}</li>)}
                            </ul>
                          </div>
                        </div>
                      </div>

                      <div className="bg-slate-950/50 p-5 rounded-2xl border border-slate-850 space-y-4">
                        <h4 className="font-bold text-white text-sm">Candidate B Comparison</h4>
                        <div className="space-y-3.5 text-xs">
                          <div>
                            <strong className="text-green-400 text-[9px] uppercase tracking-wider block mb-1">Fit Highlights</strong>
                            <ul className="list-disc pl-4 space-y-1 text-slate-400">
                              {(comparisonResult.strengthsB || []).map((s, idx) => <li key={idx}>{s}</li>)}
                            </ul>
                          </div>
                          <div>
                            <strong className="text-red-400 text-[9px] uppercase tracking-wider block mb-1">Gaps identified</strong>
                            <ul className="list-disc pl-4 space-y-1 text-slate-400">
                              {(comparisonResult.weaknessesB || []).map((w, idx) => <li key={idx}>{w}</li>)}
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="bg-purple-500/5 p-5 rounded-2xl border border-purple-500/10 text-center space-y-1">
                      <h4 className="font-bold text-violet-400 text-xs uppercase tracking-wider">Hiring Sourcing Recommendation</h4>
                      <p className="text-violet-300 font-bold text-sm">{comparisonResult.recommendation}</p>
                    </div>
                  </div>
                ) : (
                  <p className="text-center text-slate-500">Failed to load candidate metrics.</p>
                )}
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Offer Letter modal overlay */}
      <AnimatePresence>
        {showOfferModal && selectedAppForOffer && (
          <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-6">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 15 }}
              className="bg-slate-900 border border-slate-800 rounded-3xl max-w-md w-full flex flex-col shadow-2xl overflow-hidden text-left"
            >
              <div className="flex justify-between items-center p-6 border-b border-slate-850 bg-slate-950/40">
                <h3 className="text-sm font-bold text-white flex items-center gap-1">
                  ✉️ Issue Custom Offer letter
                </h3>
                <button
                  onClick={() => {
                    setShowOfferModal(false);
                    setSelectedAppForOffer(null);
                    setOfferSalary("");
                    setOfferJoiningDate("");
                  }}
                  className="text-slate-450 hover:text-white bg-slate-850 p-1.5 rounded-lg border border-slate-800 text-xs"
                >
                  ✕
                </button>
              </div>
              
              <form onSubmit={handleGenerateOfferSubmit} className="p-6 space-y-4 text-xs font-semibold">
                <div>
                  <label className="block text-slate-500 mb-1.5">Candidate</label>
                  <input
                    type="text"
                    disabled
                    value={selectedAppForOffer.candidate.fullName}
                    className="w-full bg-slate-950 border border-slate-850 rounded-xl p-3 text-slate-400 font-bold focus:outline-none"
                  />
                </div>

                <div>
                  <label className="block text-slate-400 mb-1.5">Company Name</label>
                  <input
                    type="text"
                    required
                    value={offerCompanyName}
                    onChange={(e) => setOfferCompanyName(e.target.value)}
                    placeholder="e.g. Accenture Corporate"
                    className="w-full bg-slate-950 border border-slate-855 rounded-xl p-3 text-slate-200 focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-slate-400 mb-1.5">Role Designation</label>
                  <input
                    type="text"
                    required
                    value={offerRole}
                    onChange={(e) => setOfferRole(e.target.value)}
                    placeholder="e.g. Software Engineer"
                    className="w-full bg-slate-955 border border-slate-855 rounded-xl p-3 text-slate-200 focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-slate-400 mb-1.5">CTC Package Salary (INR / Annum)</label>
                  <input
                    type="text"
                    required
                    value={offerSalary}
                    onChange={(e) => setOfferSalary(e.target.value)}
                    placeholder="e.g. 12,00,000"
                    className="w-full bg-slate-955 border border-slate-855 rounded-xl p-3 text-slate-200 focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-slate-400 mb-1.5">Joining Date</label>
                  <input
                    type="date"
                    required
                    value={offerJoiningDate}
                    onChange={(e) => setOfferJoiningDate(e.target.value)}
                    className="w-full bg-slate-955 border border-slate-855 rounded-xl p-3 text-slate-200 focus:outline-none focus:border-blue-500"
                  />
                </div>

                <button
                  type="submit"
                  disabled={generatingOffer}
                  className="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-3.5 rounded-xl transition-all shadow-md mt-2 cursor-pointer"
                >
                  {generatingOffer ? "Compiling PDF and Issuing..." : "Compile and Issue Offer Letter"}
                </button>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
};

export default Applicants;